'use strict';

/* Dashboard orchestration: CSV upload → table preview → charts.
   Charts are generated by the local data-to-chart renderer via fetch();
   if it is offline we fall back to the built-in renderer (chart-local.js). */
const RENDERER_URL = 'http://localhost:8787/api/chart';
const HEALTH_URL = 'http://localhost:8787/api/health';

const state = { headers: [], rows: [], chartType: 'bar', chart: null };
const $ = (sel) => document.querySelector(sel);

/* ---------- toast ---------- */
function toast(msg, type = 'info') {
  const t = $('#toast');
  const styles = {
    info: 'border-slate-700 bg-slate-800 text-slate-100',
    success: 'border-emerald-700 bg-emerald-900/80 text-emerald-100',
    error: 'border-red-700 bg-red-900/80 text-red-100',
  };
  t.className = `fixed bottom-6 right-6 rounded-lg border px-4 py-3 text-sm shadow-lg ${styles[type]}`;
  t.textContent = msg;
  t.classList.remove('hidden');
  clearTimeout(t._timer);
  t._timer = setTimeout(() => t.classList.add('hidden'), 3200);
}

/* ---------- renderer status ---------- */
function setBadge(online) {
  const b = $('#renderer-badge');
  if (online) {
    b.textContent = 'renderer: local API ✔';
    b.className = 'rounded-full border border-emerald-700 px-3 py-1.5 text-xs text-emerald-400';
  } else {
    b.textContent = 'renderer: built-in (API offline)';
    b.className = 'rounded-full border border-amber-700 px-3 py-1.5 text-xs text-amber-400';
  }
}
async function pingRenderer() {
  try {
    const res = await fetch(HEALTH_URL);
    setBadge(res.ok);
  } catch {
    setBadge(false);
  }
}

/* ---------- file handling ---------- */
function handleFile(file) {
  if (!file) return;
  if (!/\.csv$/i.test(file.name) && file.type !== 'text/csv') {
    toast('Please upload a .csv file', 'error');
    return;
  }
  const reader = new FileReader();
  reader.onload = (e) => {
    try {
      const data = csvToData(e.target.result);
      state.headers = data.headers;
      state.rows = data.rows;
      $('#file-name').textContent = `${file.name} · ${data.rows.length} rows × ${data.headers.length} cols`;
      onDataLoaded();
      toast(`Loaded ${data.rows.length} rows`, 'success');
    } catch (err) {
      toast('Could not parse CSV: ' + err.message, 'error');
    }
  };
  reader.onerror = () => toast('Could not read file', 'error');
  reader.readAsText(file);
}

function loadSample() {
  const data = csvToData(SAMPLE_CSV);
  state.headers = data.headers;
  state.rows = data.rows;
  $('#file-name').textContent = `sample.csv · ${data.rows.length} rows × ${data.headers.length} cols`;
  onDataLoaded();
  toast('Sample data loaded', 'success');
}

/* ---------- table preview ---------- */
function renderTable() {
  const MAX = 100;
  const shown = state.rows.slice(0, MAX);
  $('#table-head').innerHTML = '<tr>' +
    state.headers.map((h) => `<th class="whitespace-nowrap px-4 py-2 font-medium text-slate-300">${escapeHtml(h)}</th>`).join('') +
    '</tr>';
  $('#table-body').innerHTML = shown
    .map((r) => '<tr class="border-t border-slate-800/70 hover:bg-slate-800/40">' +
      state.headers.map((h) => `<td class="whitespace-nowrap px-4 py-2 text-slate-300">${escapeHtml(r[h])}</td>`).join('') +
      '</tr>')
    .join('');
  $('#row-count').textContent = state.rows.length > MAX
    ? `showing ${MAX} of ${state.rows.length} rows`
    : `${state.rows.length} rows`;
}

/* ---------- controls ---------- */
function populateControls() {
  const x = $('#x-axis'), y = $('#y-axis');
  x.innerHTML = y.innerHTML = '';
  state.headers.forEach((h) => { x.add(new Option(h, h)); y.add(new Option(h, h)); });
  const numeric = state.headers.filter((h) => state.rows.some((r) => !isNaN(parseFloat(r[h]))));
  x.value = state.headers.find((h) => !numeric.includes(h)) || state.headers[0];
  const yDefaults = numeric.slice(0, 2);
  Array.from(y.options).forEach((o) => { o.selected = yDefaults.includes(o.value); });
}

function onDataLoaded() {
  renderTable();
  populateControls();
  ['#controls-card', '#chart-card', '#table-card'].forEach((s) => $(s).classList.remove('hidden'));
  renderChart();
}

/* ---------- chart rendering: fetch() → fallback ---------- */
async function renderChart() {
  const xAxis = $('#x-axis').value;
  const yAxis = Array.from($('#y-axis').selectedOptions).map((o) => o.value);
  if (!xAxis || !yAxis.length) {
    toast('Pick a category column and at least one value column', 'info');
    return;
  }
  const payload = { type: state.chartType, xAxis, yAxis, rows: state.rows };
  let config;
  try {
    const res = await fetch(RENDERER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error('status ' + res.status);
    config = await res.json();
    setBadge(true);
  } catch (err) {
    setBadge(false);
    config = buildLocalChartConfig(payload); // offline fallback
  }
  drawChart(config);
}

function drawChart(config) {
  const ctx = $('#chart-canvas').getContext('2d');
  if (state.chart) state.chart.destroy();
  state.chart = new Chart(ctx, config);
}

/* ---------- events ---------- */
document.addEventListener('DOMContentLoaded', () => {
  const dropzone = $('#dropzone');
  const fileInput = $('#file-input');

  dropzone.addEventListener('click', () => fileInput.click());
  fileInput.addEventListener('change', (e) => handleFile(e.target.files[0]));

  ['dragenter', 'dragover'].forEach((ev) =>
    dropzone.addEventListener(ev, (e) => {
      e.preventDefault();
      dropzone.classList.add('border-indigo-500', 'bg-slate-800/40');
    }));
  ['dragleave', 'drop'].forEach((ev) =>
    dropzone.addEventListener(ev, (e) => {
      e.preventDefault();
      dropzone.classList.remove('border-indigo-500', 'bg-slate-800/40');
    }));
  dropzone.addEventListener('drop', (e) => handleFile(e.dataTransfer.files[0]));

  $('#sample-btn').addEventListener('click', () => {
    try { loadSample(); } catch (err) { toast(err.message, 'error'); }
  });

  document.querySelectorAll('.type-btn').forEach((btn) =>
    btn.addEventListener('click', () => {
      state.chartType = btn.dataset.type;
      document.querySelectorAll('.type-btn').forEach((b) => b.classList.toggle('active', b === btn));
      if (state.rows.length) renderChart();
    }));

  $('#x-axis').addEventListener('change', () => state.rows.length && renderChart());
  $('#y-axis').addEventListener('change', () => state.rows.length && renderChart());

  $('#download-btn').addEventListener('click', () => {
    if (!state.chart) return;
    const a = document.createElement('a');
    a.href = state.chart.toBase64Image('image/png', 1);
    a.download = `chart-${state.chartType}.png`;
    a.click();
  });

  pingRenderer();
});

